---
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: petclinic-deploy
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: petclinic
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: petclinic
        # Run this image
        image: qt1234.jfrog.io/workshop-docker-local/petclinic:latest
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          requests: 
            memory: "256Mi"
            cpu: "250m"
        
